Added functionality to switch type of form depending on which is rece…
UKHomeOffice/cop-ui pull request #357
Opened 2022-04-12 15:39 UTC by keenan218

### Description
Added the ability to view react forms in a read-only state and switch between react and FormIO forms depending on the form type which is received.

https://support.cop.homeoffice.gov.uk/browse/COP-10345
### To test
Check that the mechanism works to switch between the two types. This would be done by submitting a react form and a FormIO form as part of a case to make sure they can both render.
To check that react forms are read-only in a 'check-your-answers' format. There should be no ability to change any of the submitted answers.

### Notes
The formIO version is still using the old functionality for rendering with the default formIO renderer with the fields disabled. There is another ticket in progress still which will allow the formIO forms to look very similar to the react forms so users should not be able to tell which type of form they have received.

2022-04-13 15:01 UTC, gardnersam requested changes

2022-04-14 09:04 UTC, keenan218 commented on client/src/pages/cases/components/CaseCheckYourAnswers.jsx
> +          data.cya = {
Regardless of what the original json was we are manually changing the type of form to be a hub-and-spoke form with the page set to the 'check your answers' page. Also specifying for there to be no page titles and actions buttons. The `actions` are the little 'change' links on a check your answers form so as we are implementing this as a read only version we need them gone in all scenarios. The forced removal of page titles is there to make the end result look a lot more concise.

2022-04-14 09:09 UTC, keenan218 commented on client/src/pages/cases/components/CaseCheckYourAnswers.jsx
> +          formSelected: formVersionId,
will remove, thanks

2022-04-14 09:13 UTC, keenan218 commented on client/src/pages/cases/components/CaseCheckYourAnswers.jsx
> +    fetchForm(formName);
fixed it now

2022-04-14 09:20 UTC, keenan218 commented on client/src/pages/cases/components/CaseCheckYourAnswers.jsx
> +  }, [axiosInstance]);
Yep you are correct, have added these in along with `formVersionId` also

2022-04-14 09:26 UTC, keenan218 commented on client/src/pages/cases/components/CaseCheckYourAnswers.jsx
> +      {renderer === 'form.io' ? (
Yep, we have changed this over now, thanks

2022-04-14 09:30 UTC, keenan218 commented on client/src/pages/cases/components/CaseCheckYourAnswers.jsx
> +        //  <SummaryList
Added a comment for these, currently awaiting another ticket being finalised to be uncommented and functional, we can remove them for now if you'd rather that?

2022-04-14 09:36 UTC, keenan218 commented on client/src/pages/cases/components/CaseCheckYourAnswers.jsx
> +          style={{ border: '#000000 solid 1px', padding: '10px' }}
Have moved this

2022-04-14 09:41 UTC, keenan218 commented on client/src/pages/cases/components/CaseCheckYourAnswers.jsx
> +          noChangeAction
The collection of those props will make the form render as a read-only form by removing the change buttons, the titles and removing the separator lines.

2022-04-14 09:48 UTC, keenan218 commented on client/src/pages/cases/components/CaseCheckYourAnswers.test.jsx
> +    dataPath: 'businessKey-12345/recordBorderEvent/test-file-two.json',
removed

2022-04-14 09:56 UTC, keenan218 commented on client/src/pages/cases/utils/ReactForm.json
> +{
Yep, have changed this now

2022-04-20 08:50 UTC, gardnersam reviewed
One dependency under question, otherwise looking good

2022-04-20 08:50 UTC, gardnersam commented on client/package.json
> +    "regenerator-runtime": "^0.13.9",
could this be in devDependencies below?

2022-04-20 08:50 UTC, gardnersam commented on client/src/pages/cases/components/CaseCheckYourAnswers.test.jsx
> +import 'regenerator-runtime/runtime';
actually is this used here?

2022-04-20 08:57 UTC, keenan218 commented on client/package.json
> +    "regenerator-runtime": "^0.13.9",
Yep, will move this

2022-04-20 09:05 UTC, keenan218 commented on client/src/pages/cases/components/CaseCheckYourAnswers.test.jsx
> +import 'regenerator-runtime/runtime';
Yeah the test wanted us to import this since it is 'undefined' when running in console

2022-04-20 09:08 UTC, gardnersam approved these changes
Looks good!

2022-04-20 09:11 UTC, merged