WIP - COP-10221 - People component
UKHomeOffice/cop-ui pull request #441
Opened 2022-07-21 22:18 UTC by charles474

# Description
This PR ...

2022-07-26 11:38 UTC, Shaks approved these changes
lgtm

2022-08-12 08:32 UTC, Shaks requested changes

2022-08-12 08:32 UTC, Shaks commented on client/src/pages/targets/airpax/TargetInfoPage.jsx
> +  const clearAccordionStorage = () => {
Could we implement the same solution here you did for cerberus yesterday and remove this method?

2022-08-12 08:32 UTC, Shaks commented on client/src/pages/targets/airpax/TargetInfoPage.jsx
> +   */
Same here as above for this method

2022-08-12 08:32 UTC, Shaks commented on client/src/pages/targets/airpax/TargetInfoPage.jsx
> +      setTargetData();
Add error handling here

2022-08-12 08:32 UTC, Shaks commented on client/src/pages/targets/airpax/TargetInfoPage.jsx
> +
Remove this useEffect

2022-08-12 08:32 UTC, Shaks commented on client/src/pages/targets/airpax/TargetsListPage.jsx
>        setTaskCount(0);
set the error state here too

2022-08-12 08:33 UTC, charles474 commented on client/src/pages/targets/airpax/TargetInfoPage.jsx
> +      setTargetData();
I don't believe we have any error handling on this page, along with RoRo page either. I did spot that but i'll have to do that in another ticket. I'm trying to avoid mixing anything at the moment.

2022-08-12 08:34 UTC, charles474 commented on client/src/pages/targets/airpax/TargetInfoPage.jsx
> +  const clearAccordionStorage = () => {
This will come in another follow up ticket.

2022-08-12 08:34 UTC, charles474 commented on client/src/pages/targets/airpax/TargetsListPage.jsx
>        setTaskCount(0);
Similar to the comment here https://github.com/UKHomeOffice/cop-ui/pull/441#discussion_r944237457.

2022-08-12 15:20 UTC, Shaks approved these changes
lgtm

2022-08-12 15:21 UTC, merged