COP-11942: Implmented confirmation of receipt at FE
UKHomeOffice/cop-ui pull request #543
Opened 2022-09-26 08:36 UTC by Shaks

**Confirm receipt** targets would appear in **Receipted** tab

![image](https://user-images.githubusercontent.com/1534608/192231125-b1cdaee4-d229-454b-bc30-a60134e9c5f0.png)

2022-09-26 15:15 UTC, charles474 commented on client/src/utils/constants.js
>  export const TARGET_STATUS_NEW = 'NEW';
Suggestion rather than a must, if we can group this together within an object

e.g. 

```
export const TASK_STATUS = {
  NEW: 'new',
  CAPTURED: 'captured',
  RECEIPTED: 'receipted',
}
```

Same for the `TARGET_STATUSES` all grouped by `TARGET_STATUS` object.

2022-09-26 20:19 UTC, Shaks commented on client/src/utils/constants.js
>  export const TARGET_STATUS_NEW = 'NEW';
Group them both TASK and TARGET_STASUSES

2022-09-26 20:58 UTC, charles474 commented on client/src/pages/targets/__components__/TargetListItemOptions.jsx
> +          View details
Why do we have 2 buttons that do the exact same thing. From the looks of it, you've added a second button and forgotten to attach an onClick handler to it.

Regardless, we don't need two buttons that should do the exact same thing.

2022-09-26 21:07 UTC, charles474 requested changes
Also looking through the code, we know which endpoint we need to call to get the number of counts if you're a part of an `Airpax` group. The code you added to the `index.jsx` located at the following path `src/pages/home/index.jsx` on the following lines https://github.com/UKHomeOffice/cop-ui/blob/COP-11942/client/src/pages/home/index.jsx#L173-L202,  I don't fully understand why the code there has not yet been updated considering that we can now call the cop-targeting-api locally and we know the parameters that also need to pass to the api.

Try and remember these unfinished portions of code as it is just a bug waiting to happen if it ever made it into production and a user is purely a member of airpax groups only.

2022-09-26 21:16 UTC, charles474 commented on client/src/pages/targets/airpax/TargetsListPage.jsx
> +  const tabStatusMapper = {
This simple mapper is doing too much, it's also converting to an array.

it really should just be 

```
const tabStatusMapper = {
    new: TARGET_STATUS.NEW,
    receipted: TARGET_STATUS.RECEIPTED,
    captured: TARGET_STATUS.CAPTURED,
  };
```

The comment below then shows how the mapper can then be used.

2022-09-27 07:27 UTC, Shaks commented on client/src/pages/targets/__components__/TargetListItemOptions.jsx
> +          View details
You are right. I have a added an OR condition to the button code to take care of TASK_STATUS.RECEIPTED

2022-09-27 10:04 UTC, Shaks commented on client/src/pages/targets/airpax/TargetsListPage.jsx
> +  const createTargetStatusArray = () => tabStatusMapper[selectedTab];
fixed

2022-09-27 10:04 UTC, Shaks commented on client/src/pages/targets/airpax/TargetsListPage.jsx
> +  const tabStatusMapper = {
fixed

2022-09-27 10:32 UTC, charles474 commented on client/src/pages/targets/airpax/TargetsListPage.jsx
> +  const tabStatusMapper = {
Apologies, I should have seen this also, This really should live a lot higher up this file than randomly in between code.

2022-09-27 10:32 UTC, charles474 commented on client/src/pages/targets/airpax/TargetsListPage.jsx
> +    console.log('selectedTab ', selectedTab);
`console.log` not required.

2022-09-27 10:36 UTC, charles474 reviewed
Also apply the tab fix to RoRo V1 for consistency.

2022-09-27 10:41 UTC, Shaks commented on client/src/pages/targets/airpax/TargetsListPage.jsx
> +    console.log('selectedTab ', selectedTab);
My bad

2022-09-27 12:19 UTC, charles474 commented on client/src/pages/targets/routes.js
> +          <TaskSelectedTabProvider>
You need to revert this change here as this is the original targets list page.

2022-09-27 12:26 UTC, Shaks commented on client/src/pages/targets/routes.js
> +          <TaskSelectedTabProvider>
The issue got fixed applying this change here too

2022-09-27 12:32 UTC, charles474 approved these changes
Thanks for making those changes.

2022-09-27 12:52 UTC, merged